INSERT INTO Location (id, state, city, locality, createdBy, updatedBy, createdAt, updatedAt)
VALUES
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'AGCR Enclave', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'AIIMS', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aali', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aashirwaad Chowk', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Abhey Garden', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Abul Fazal Enclave Part 1', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Abul Fazal Enclave Part 2', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Acharya Niketan', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Adarsh Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Adhchini', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Adhyapak Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aero City', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Africa Avenue', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Agar Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ajit Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'haryana', 'Gurgaon', 'Aath Marla', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'haryana', 'Gurgaon', 'Acharya Puri', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'Uttar Pradesh', 'Noida', 'Aghapur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'Uttar Pradesh', 'Greater Noida', 'Ace Divino', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ajmeri Gate', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Akash Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Akbarpur Majra', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Alaknanda', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ali Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aliganj', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Alipur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aman Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Amar Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ambar Hai Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ambica Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Amrita Shergill Marg', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Amritpuri', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anand Gram', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anand Lok', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anand Niketan', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anand Parbat', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anand Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anarkali Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Andheria Mor', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Andrews Ganj', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ansari Nagar East', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ansari Nagar West', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ansari Road', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anup Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Anupam Garden', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aps Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aradhana Enclave', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aram Bagh', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Arjun Garh', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Arjun Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Arjun Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aruna Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Arya Pura', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Asaf Ali Road', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Asalatpur Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Asha Park', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ashok Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ashok Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ashoka Niketan', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ashram', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Asiad village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Asmara Lines', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Asola', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Auchandi', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aurobindo Marg', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Aya Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ayur Vigyan Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Azad Market', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Azad Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Azadpur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Azim Dairy', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baba Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baba Kharak Singh Marg Area', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baba Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Babar Road', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Babarpur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Babu Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Badarpur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Badhosra', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Badli', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Badu Sarai', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bagdola', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bagiabad', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bahapur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baird Place', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bakarwala', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bakhtawarpur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Balbir Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bali Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baljit Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baljit Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ballabgarh', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bamnoli Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bangali Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bank Enclave', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bankner', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bankoli', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bapa Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bapraula', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baqar Garh', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bara Hindu Rao', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baradari', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Barakhamba', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Baraula Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Barwala', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Basai Darapur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Basant Gaon', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Basant Lok', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Batla House', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bawana', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bazidpur Thakran', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Begam Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Begampur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Beholpur Bangar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bengali Market', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Ber Sarai', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagat Singh Market', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagat Singh Park', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagat Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagirathi Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagwan Das Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagwan Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagwanpur Khera', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagwati Garden', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagwati Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhagya Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhai Vir Singh Marg Area', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhajanpura', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhalswa', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bharat Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bharat Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bharola', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bharthal', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bharti Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhati Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhavishyanidhi Enclave', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhera Enclave', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhikaji Cama Place', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhogal', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhola Nath Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhorgarh', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bhuli Bhatiyari', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bihari Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Biharipur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bijwasan', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bindapur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bk Dutt Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bodella', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Brahmpuri', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Budh Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Budh Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Budhanpur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Budhela Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Budhpur Bijapur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Bulla Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Burari', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'CC Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Cariappa Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Central Ridge Forest Area', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Central Secretariat', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chaman Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chanakya Place', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chanakyapuri', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chand Bagh', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chand Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandan Hola', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandan Singh Park', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandan Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chander Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chander Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chanderlok', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandni Chowk', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandni Mahal', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandpur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandra Nagar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chandrawal', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chattarpurc', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chauhan Bangar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chawri Bazar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chhajjupur', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chhawla', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chilla', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chirag Delhi', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chitra Vihar', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chitrakoot', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chitral Lines', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chittaranjan Park', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chokhandi', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Chuna Mandi', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Civil Aviation Colony', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Civil Lines', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Commonwealth Games Village', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'Connaught Place', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
(REPLACE(UUID(), '-', ''), 'delhi', 'delhi', 'DND Flyover Area', 'system', 'system', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6));


-- Data from the image
INSERT INTO Location (id, state, stateImageUrl, city, cityImageUrl, locality, createdBy, updatedBy, createdAt, updatedAt)
VALUES
  (REPLACE(UUID(), '-', ''), 'haryana', NULL, 'Gurgaon', NULL, 'Aath Marla', 'system', 'system', NOW(6), NOW(6)),
  (REPLACE(UUID(), '-', ''), 'haryana', NULL, 'Gurgaon', NULL, 'Acharya Puri', 'system', 'system', NOW(6), NOW(6)),
  (REPLACE(UUID(), '-', ''), 'haryana', NULL, 'Gurgaon', NULL, 'Adarsh Nagar', 'system', 'system', NOW(6), NOW(6)),
  (REPLACE(UUID(), '-', ''), 'haryana', NULL, 'Gurgaon', NULL, 'Airforce Station', 'system', 'system', NOW(6), NOW(6));

-- Data from the provided object
INSERT INTO Location (id, state, stateImageUrl, city, cityImageUrl, locality, createdBy, updatedBy, createdAt, updatedAt)
VALUES
  (REPLACE(UUID(), '-', ''), 'Madhya Pradesh', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Upper_Lake%2C_Bhopal.jpg/800px-Upper_Lake%2C_Bhopal.jpg', 'Bhopal', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Upper_Lake%2C_Bhopal.jpg/800px-Upper_Lake%2C_Bhopal.jpg', 'MP Nagar', 'system', 'system', NOW(6), NOW(6)),
  (REPLACE(UUID(), '-', ''), 'Madhya Pradesh', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Upper_Lake%2C_Bhopal.jpg/800px-Upper_Lake%2C_Bhopal.jpg', 'Bhopal', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Upper_Lake%2C_Bhopal.jpg/800px-Upper_Lake%2C_Bhopal.jpg', 'Arera Colony', 'system', 'system', NOW(6), NOW(6)),
  (REPLACE(UUID(), '-', ''), 'Madhya Pradesh', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Upper_Lake%2C_Bhopal.jpg/800px-Upper_Lake%2C_Bhopal.jpg', 'Indore', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Rajwada%2C_Indore.jpg/800px-Rajwada%2C_Indore.jpg', 'Vijay Nagar', 'system', 'system', NOW(6), NOW(6)),
  (REPLACE(UUID(), '-', ''), 'Madhya Pradesh', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Upper_Lake%2C_Bhopal.jpg/800px-Upper_Lake%2C_Bhopal.jpg', 'Indore', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Rajwada%2C_Indore.jpg/800px-Rajwada%2C_Indore.jpg', 'Saket', 'system', 'system', NOW(6), NOW(6));